name: rho
channels:
  - conda-forge
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2022.12.7
  - entrypoints=0.4
  - jupyter_client=7.4.8
  - jupyter_core=5.1.2
  - libcxx=14.0.6
  - libffi=3.4.2
  - libsodium=1.0.18
  - libsqlite=3.40.0
  - libzlib=1.2.13
  - nb_conda_kernels=2.3.1
  - ncurses=6.3
  - nest-asyncio=1.5.6
  - openssl=3.0.7
  - pip=22.3.1
  - platformdirs=2.6.2
  - python=3.10.8
  - python-dateutil=2.8.2
  - python_abi=3.10
  - pyzmq=24.0.1
  - readline=8.1.2
  - setuptools=65.6.3
  - six=1.16.0
  - tk=8.6.12
  - tornado=6.2
  - traitlets=5.8.0
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - tzdata=2022g
  - wheel=0.38.4
  - xz=5.2.6
  - zeromq=4.3.4
  - pip:
    - anyio==3.6.2
    - appnope==0.1.3
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.2.3
    - ase==3.22.1
    - asttokens==2.2.1
    - attrs==22.2.0
    - babel==2.11.0
    - backcall==0.2.0
    - beautifulsoup4==4.11.1
    - bleach==5.0.1
    - certifi==2022.12.7
    - cffi==1.15.1
    - charset-normalizer==3.0.1
    - cmake==3.25.0
    - comm==0.1.2
    - contourpy==1.0.6
    - cycler==0.11.0
    - debugpy==1.6.5
    - decorator==5.1.1
    - defusedxml==0.7.1
    - executing==1.2.0
    - fastjsonschema==2.16.2
    - fonttools==4.38.0
    - fqdn==1.5.1
    - h5py==3.7.0
    - idna==3.4
    - ipykernel==6.19.4
    - ipython==8.8.0
    - ipython-genutils==0.2.0
    - ipywidgets==8.0.4
    - isoduration==20.11.0
    - jedi==0.18.2
    - jinja2==3.1.2
    - joblib==1.2.0
    - json5==0.9.11
    - jsonpointer==2.3
    - jsonschema==4.17.3
    - jupyter==1.0.0
    - jupyter-console==6.4.4
    - jupyter-events==0.5.0
    - jupyter-server==2.0.6
    - jupyter-server-terminals==0.4.3
    - jupyterlab==3.5.3
    - jupyterlab-pygments==0.2.2
    - jupyterlab-server==2.19.0
    - jupyterlab-widgets==3.0.5
    - kaleido==0.2.1
    - kiwisolver==1.4.4
    - markupsafe==2.1.1
    - matplotlib==3.6.2
    - matplotlib-inline==0.1.6
    - mistune==2.0.4
    - mpltex==0.7
    - mpmath==1.2.1
    - nbclassic==0.4.8
    - nbclient==0.7.2
    - nbconvert==7.2.7
    - nbformat==5.7.1
    - nodejs==0.1.1
    - notebook==6.5.2
    - notebook-shim==0.2.2
    - npm==0.1.1
    - numpy==1.24.1
    - optional-django==0.1.0
    - packaging==22.0
    - palettable==3.3.0
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==9.4.0
    - prometheus-client==0.15.0
    - prompt-toolkit==3.0.36
    - psutil==5.9.4
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - py3dmol==2.0.0.post2
    - pycparser==2.21
    - pygments==2.14.0
    - pyparsing==3.0.9
    - pyrsistent==0.19.3
    - pyscf==2.1.1
    - python-json-logger==2.0.4
    - pytz==2022.7.1
    - pyyaml==6.0
    - qtconsole==5.4.0
    - qtpy==2.3.0
    - requests==2.28.2
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - scipy==1.10.0
    - send2trash==1.8.0
    - sniffio==1.3.0
    - soupsieve==2.3.2.post1
    - stack-data==0.6.2
    - sympy==1.11.1
    - tenacity==8.1.0
    - terminado==0.17.1
    - tinycss2==1.2.1
    - tomli==2.0.1
    - torch==1.13.1
    - tqdm==4.64.1
    - uri-template==1.2.0
    - urllib3==1.26.14
    - wcwidth==0.2.5
    - webcolors==1.12
    - webencodings==0.5.1
    - websocket-client==1.4.2
    - widgetsnbextension==4.0.5
    - wigners==0.2.1
prefix: /opt/miniforge3/envs/rho
